### ISSUE TITLE
"Use Signature" bug

### ISSUE THREAD

**Issue by mcculloughcm** [danhowellnz/SendEmail#5]
Hi! First of all, thank you for making this -- it's super helpful!

I did find a small bug around the "Use Signature" option. I was trying to turn "Use Signature" off when we're sending from Org Wide Addresses, but found that there was no way to stop the running user's signature from showing up if they had one set.

I think the issue is on line 370:
`if (request.UseSignature == true) mail.setUseSignature(true);`

The [setUseSignature method defaults to true](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_email_outbound_base.htm), and setting request.UseSignature to False won't update mail.setUseSignature. I think just flipping this line would do the trick:

`if (request.UseSignature == false) mail.setUseSignature(false);`

**Comment by danhowellnz** [comment]
Thanks, will be updated
